import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        blue: {
          4: "var(--blue-4)",
          5: "var(--blue-5)",
          6: "var(--blue-6)",
          7: "var(--blue-7)",
          8: "var(--blue-8)",
          9: "var(--blue-9)",
          10: "var(--blue-10)",
          11: "var(--blue-11)",
          12: "var(--blue-12)",
        },
        red: {
          1: "var(--red-1)",
          2: "var(--red-2)",
          3: "var(--red-3)",
          4: "var(--red-4)",
          5: "var(--red-5)",
          6: "var(--red-6)",
          7: "var(--red-7)",
          8: "var(--red-8)",
          9: "var(--red-9)",
          10: "var(--red-10)",
          11: "var(--red-11)",
          12: "var(--red-12)",
        },
        gray: {
          1: "var(--gray-1)",
          2: "var(--gray-2)",
          3: "var(--gray-3)",
          4: "var(--gray-4)",
          5: "var(--gray-5)",
          6: "var(--gray-6)",
          7: "var(--gray-7)",
          8: "var(--gray-8)",
          9: "var(--gray-9)",
          10: "var(--gray-10)",
          11: "var(--gray-11)",
          12: "var(--gray-12)",
        },
        violet: {
          1: "var(--violet-1)",
          2: "var(--violet-2)",
          3: "var(--violet-3)",
          4: "var(--violet-4)",
          5: "var(--violet-5)",
          6: "var(--violet-6)",
          7: "var(--violet-7)",
          8: "var(--violet-8)",
          9: "var(--violet-9)",
          10: "var(--violet-10)",
          11: "var(--violet-11)",
          12: "var(--violet-12)",
        },
        mauve: {
          1: "var(--mauve-1)",
          2: "var(--mauve-2)",
          3: "var(--mauve-3)",
          4: "var(--mauve-4)",
          5: "var(--mauve-5)",
          6: "var(--mauve-6)",
          7: "var(--mauve-7)",
          8: "var(--mauve-8)",
          9: "var(--mauve-9)",
          10: "var(--mauve-10)",
          11: "var(--mauve-11)",
          12: "var(--mauve-12)",
        },
        olive: {
          1: "var(--olive-1)",
          2: "var(--olive-2)",
          3: "var(--olive-3)",
          4: "var(--olive-4)",
          5: "var(--olive-5)",
          6: "var(--olive-6)",
          7: "var(--olive-7)",
          8: "var(--olive-8)",
          9: "var(--olive-9)",
          10: "var(--olive-10)",
          11: "var(--olive-11)",
          12: "var(--olive-12)",
        },
        sage: {
          1: "var(--sage-1)",
          2: "var(--sage-2)",
          3: "var(--sage-3)",
          4: "var(--sage-4)",
          5: "var(--sage-5)",
          6: "var(--sage-6)",
          7: "var(--sage-7)",
          8: "var(--sage-8)",
          9: "var(--sage-9)",
          10: "var(--sage-10)",
          11: "var(--sage-11)",
          12: "var(--sage-12)",
        },
      },
    },
  },
  plugins: [],
};
export default config;
