import { Theme, ThemePanel } from "@radix-ui/themes";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header";
import ThemeProviding from "@/components/ThemeProviding";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`relative ${inter.className}`}>
        <ThemeProviding class="h-full">
          <Theme appearance="light">
            <Header />
            {children}
          </Theme>
        </ThemeProviding>
      </body>
    </html>
  );
}
